const Data = [
    {
        duration : 'Monthly',
        name:'Social Plus',
        dat: '10GB Data (Whatsap,IMO & Facebook)',
        minutes:'300 jazz Minutes',
        ominutes:'50 Other network minutes',
        sms:'300',
        balance:'215',
        img:'../Images/sargodha.png',
    },
    {
        duration : 'Bemisaal',
        name:'OFFER 1',
        dat: '3GB Data Free Whatsapp',
        minutes:'1000 jazz Minutes',
        ominutes:'30 Other network minutes',
        sms:'1000',
        balance:'87',
        img:'../Images/Prepaid.png',
    },
    {
        duration : 'Bemisaal',
        name:'OFFER 2',
        dat: '3GB+Free Whatsapp ',
        minutes:'1000 jazz Minutes',
        ominutes:'30 Other network minutes',
        sms:'1000',
        balance:'87',
        img:'../Images/banner-mobile.png',
    },
    {
        duration : 'Bemisal',
        name:'Offer-3',
        dat: '3GB+Data Whatsap',
        minutes:'1000 jazz Minutes',
        ominutes:'30 Other network minutes',
        sms:'1000',
        balance:'87',
        img:'../Images/Postpaid.png',
    },
    {
        duration : 'Monthly',
        name:'SUPER DUPER',
        dat: '12GB Data',
        minutes:'3000 jazz Minutes',
        ominutes:'300 Other network minutes',
        sms:'3000',
        balance:'780',
        img:'../Images/banner-mobile.png',
    },
    {
        duration : 'Weekly',
        name:'SUPER PLUS',
        dat: '10GB Data',
        minutes:'5000 jazz Minutes',
        ominutes:'100 Other network minutes',
        sms:'5000',
        balance:'304',
        img:'../Images/Container.png',
    },
    {
        duration : 'Weekly',
        name:'WHATSAPP', 
        dat: '25 MB Whatsap',
        minutes:'0 jazz Minutes',
        ominutes:'0 Other network minutes',
        sms:'1500',
        balance:'30',
        img:'../Images/ConHead.png',
    },
];
export default Data;